server:
  port: 8081
logging:
  level:
    root: info


spring:
  security:
    user:
      name: user
      password: 12345678
      roles: admin,user
  messages:
    basename: messages
    encoding: UTF-8