server:
  port: 8081
logging:
  level:
    root: info

spring:
  messages:
    always-use-message-format: false
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
  datasource:
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      pool-name: Hikari
    password: Sql@#123
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://110.42.248.225:3306/qqq?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  devtools:
    add-properties: false
    livereload:
      enabled: false
    restart:
      enabled: false
#mybatis
mybatis:
  type-aliases-package: com.uaa.domain #别名
  mapper-locations: classpath:xml/*.xml #xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mooc:
  email-provider:
    api-key: ${EMAIL_API_KEY}
    name: api
  jwt:
    access-token-expire-time: 300000
    header: Authorization
    prefix: "Bearer "
    refresh-token-expire-time: 2592000000
    #${JWT_KEY}
    key: 5YWo5aWH5p2D5piv5Liq5aSn5biF5ZOl77yM5ZOI5ZOI5ZOI5ZOI5ZOI77yM5Lu75bCR5a6H5piv5Liq5aSn576O5aWz77yM5bCP5p+S5p+S5Lmf5piv5Liq5aSn576O5aWz
    #${JWT_REFRESH_KEY}
    refresh-key: 5YWo5aWH5p2D5piv5Liq5aSn5biF5ZOl77yM5ZOI5ZOI5ZOI5ZOI5ZOI77yM5Lu75bCR5a6H5piv5Liq5aSn576O5aWz77yM5bCP5p+S5p+S5Lmf5piv5Liq5aSn576O5aWz
  security:
    role-hierarchy-enabled: true
  sms-provider:
    api-url: ${SMS_API_URL}
    name: ${SMS_PROVIDER_NAME}
  lean-cloud:
    app-id: ${LEAN_CLOUD_APP_ID}
    app-key: ${LEAN_CLOUD_APP_KEY}
  ali:
    api-key: ${ALI_API_KEY}
    api-secret: ${ALI_API_SECRET}
